version: '3.7'

services:
  ts-node:
    container_name: ts-node
    build:
      context: .
      target: base
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    env_file:
      - ./env/.ts-node.env
    depends_on:
      - db
      # - localstack
    command: npm run start
  db:
    build: .docker/postgres
    container_name: tasks-db
    restart: always
    tty: true
    env_file:
      - ./env/.postgres.env
    ports: 
      - '5432:5432'    
    volumes: 
      - .docker/dbdata:/var/lib/postgresql/data

  # localstack:
  #   image: localstack/localstack:latest
  #   env_file:
  #     - ./env/.localstack.env
  #   ports:
  #     - '4566:4566'
  #   volumes:
  #     - "${TMPDIR:-/tmp/localstack}:/var/lib/localstack"
  #     - "/var/run/docker.sock:/var/run/docker.sock"