export POSTGRES_PASSWORD=root
export POSTGRES_DB=task

TYPEORM_CONNECTION=postgres
TYPEORM_HOST=db
TYPEORM_DATABASE=task-prod
TYPEORM_USERNAME=postgres
TYPEORM_PASSWORD=root
TYPEORM_PORT=5432
PORT=3001
EXTERNAL_PORT=3001